/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestCcLib */

#ifndef _Included_TestCcLib
#define _Included_TestCcLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestCcLib
 * Method:    callC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_TestCcLib_callC
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
